
let adjective = "Huge";
let noun = "dragon";
let verb = "gets angry";
let place = "Forests";
let adjective2 = "Huge body";
let noun2 = "Meat";

let firstStory =
"Once upon a time, there was a(n) " + adjective + " " + noun +
" who loved to eat " + noun2 + ". The " + noun +
" lived in a " + place +
" and had " + adjective2 +
" nostrils that blew fire when it was " + verb + ".";

console.log("First story: " + firstStory);

adjective = "fire";
noun = "fox";
verb = "gets angry";
place = "desert";
adjective2 = "terrifying sound";
noun2 = "Meat";

let secondStory =
"Once upon a time, there was a(n) " + adjective + " " + noun +
" who loved to eat " + noun2 + ". The " + noun +
" lived in a " + place +
" and had " + adjective2 +
" nostrils that blew fire when it was " + verb + ".";

console.log("Second story: " + secondStory);
