let greeting = "Hello! I'm your coding fun fact guide!";
console.log(greeting);

let botName = "haneen";
let botLocation = "the universe";
let favoriteLanguage = "javascript";

console.log("My name is " + botName + " and I live on " + botLocation + ".");
console.log("My favorite programming language is " + favoriteLanguage + ".");

let codingFact = favoriteLanguage + " Works almost everywhere: browsers, servers (Node.js), mobile apps, and even games.";
console.log(codingFact);

codingFact = favoriteLanguage + " :Second fact , The foundation of the modern web, most interactive websites rely on it fundamentally.";
console.log(codingFact);

codingFact = favoriteLanguage + " :Another fact , Its name has nothing to do with Java: the name was chosen solely for marketing reasons, and the two languages are completely different.";
console.log(codingFact);

console.log("It was fun sharing these facts with you. Goodbye! - " + botName + " from " + botLocation + ".");